version: '3'
services:
#mssql docker
  kinocentar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LPbXJXDVcU85rdtP!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - kinocentar-net

  kinocentar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:KinoCentarDbContext=Server=kinocentar-sql,1433;Database=KinoCentarDB;User=sa;Password=LPbXJXDVcU85rdtP!;ConnectRetryCount=0
    ports:
      - 5000:5050
    networks:
      - kinocentar-net      
    links:
      - kinocentar-sql
    depends_on:
      - kinocentar-sql
      
networks:
  kinocentar-net:
    driver: bridge      